artifacts_root : artifacts 


data_ingestion :
  root_dir : artifacts/data_ingestion
  source_url : https://github.com/shahabas9/datasets/raw/main/data.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion

data_validation :
  root_dir : artifacts/data_validation
  unzip_data_dir : artifacts/data_ingestion/data/DataCoSupplyChainDataset.csv
  STATUS_FILE : artifacts/data_validation/status.txt

data_transformation :
  root_dir : artifacts/data_transformation
  data_dir :  artifacts/data_ingestion/data/DataCoSupplyChainDataset.csv
  scaler_path : artifacts/data_transformation/scaler.pkl
  model_feature_path : artifacts/data_transformation/rfr.pkl
  one_hot_encoder_path : artifacts/data_transformation/onehot_encoder.pkl
  transformed_data :  artifacts/data_transformation/transformed_data.csv
  preprocessed_dir :  artifacts/data_transformation/preprocessed_data.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  